version: '3'

services:
  traefik:
    image: traefik:v2.5
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    labels:
      - traefik.http.routers.api.rule=Host(`monitor.sonarft.com`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
      - traefik.http.routers.api.middlewares=dashboard-auth
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USERS}"

  sonarft:
    image: sonarft:latest
    volumes:
      - sonarft_history:/app/sonarftdata/history
      - sonarft_bots:/app/sonarftdata/bots
    labels:
      - traefik.http.routers.sonarft.rule=Host(`sonarft.com`)
      - traefik.http.routers.sonarft.entrypoints=websecure
      - traefik.http.routers.sonarft.tls.certresolver=myresolver
      - traefik.http.services.sonarft.loadbalancer.server.port=5000

volumes:
  sonarft_history:
  sonarft_bots:
